package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"
	"fire-go/graph/model"
	"fire-go/internal/utils"
	"fmt"
)

// Deforestation is the resolver for the deforestation field.
func (r *queryResolver) Deforestation(ctx context.Context, id string) (*model.Deforestation, error) {
	var deforestation model.Deforestation
	query := `SELECT id FROM deforestation_intersect WHERE id = $1`
	err := r.DB.QueryRow(ctx, query, id).Scan(&deforestation.ID)
	if err != nil {
		return nil, fmt.Errorf("erro ao buscar deforestation: %v", err)
	}
	return &deforestation, nil
}

// Deforestations is the resolver for the deforestations field.
func (r *queryResolver) Deforestations(ctx context.Context) ([]*model.Deforestation, error) {
	query := `SELECT id FROM deforestation_intersect ORDER BY id`
	rows, err := r.DB.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("erro ao buscar deforestations: %v", err)
	}
	defer rows.Close()

	var deforestations []*model.Deforestation
	for rows.Next() {
		var d model.Deforestation
		if err := rows.Scan(&d.ID); err != nil {
			return nil, fmt.Errorf("erro ao escanear deforestation: %v", err)
		}
		deforestations = append(deforestations, &d)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("erro ao iterar rows: %v", err)
	}

	return deforestations, nil
}

// Fire is the resolver for the fire field.
func (r *queryResolver) Fire(ctx context.Context) ([]*model.Fire, error) {
	query := `SELECT id,type,municipality_id,year,month,area_ha,geom FROM fire_intersect ORDER BY id`
	rows, err := r.DB.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("erro ao buscar fire %v", err)
	}
	defer rows.Close()

	var Fire []*model.Fire
	for rows.Next() {
		var d model.Fire
		if err := rows.Scan(&d.ID, &d.Type, &d.MunicipalityID, &d.Year, &d.Month, &d.AreaHa, &d.Geom); err != nil {
			return nil, fmt.Errorf("erro ao escanear fire: %v", err)
		}
		geojson, err := utils.EWKBHexToGeoJSON(*d.Geom)
		if err != nil {
			return nil, fmt.Errorf("erro ao converter geom para geojson: %v", err)
		}
		d.Geom = &geojson
		Fire = append(Fire, &d)
	}

	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("erro ao iterar rows: %v", err)
	}

	return Fire, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
