// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Deforestation struct {
	ID string `json:"id"`
}

type Fire struct {
	ID             string  `json:"id"`
	Type           string  `json:"type"`
	MunicipalityID int32   `json:"MunicipalityID"`
	Year           string  `json:"Year"`
	Month          string  `json:"Month"`
	AreaHa         string  `json:"AreaHa"`
	Geom           *string `json:"Geom,omitempty"`
}

type Query struct {
}
